max-credits: 100001
max-credits-owner: 694201337
start-credits: 1000

costs:
  other: 10

  chat-models:
    gpt-4-32k: 100
    gpt-4: 30
    gpt-3: 5

## Roles Explanation

# Bonuses: They are a multiplier for costs
#          They work like: final_cost = cost * bonus

roles:
  owner:
    bonus: 0
  admin:
    bonus: 0.2
  helper:
    bonus: 0.4
  booster:
    bonus: 0.6
  default:
    bonus: 1.0
